server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/plain application/javascript application/json text/css;

    location ~* \.(js|css|png|jpg|jpeg|svg|ico|woff2?)$ {
        expires 30d;
        access_log off;
    }
}